FROM golang:1.24-alpine AS build
WORKDIR /src
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN go build -o /out/examora-worker ./cmd/worker

FROM alpine:3.21
COPY --from=build /out/examora-worker /usr/local/bin/examora-worker
CMD ["examora-worker"]
